import { mutation } from "./_generated/server";

const PH = "https://placehold.co/600x600/0d1117/f5a623?text=";

type V = {
  storage: string;
  simType?: "physical-sim" | "esim" | "wifi" | "wifi-5g";
  color?: string;
  price: number;
  stock: number;
};
type P = {
  name: string;
  slug: string;
  description: string;
  category: string;
  brand?: string;
  condition: "brand-new" | "ex-uk" | "ex-usa";
  price: number;
  compareAtPrice?: number;
  images: string[];
  specs?: Record<string, string>;
  stock: number;
  isActive: boolean;
  isFeatured: boolean;
  isHotDeal: boolean;
  isNewArrival: boolean;
  variants?: V[];
};

const products: P[] = [
  // ─── EX-USA iPhones ───────────────────────────────────────────────
  {
    name: "iPhone 12 Pro 256GB — Ex USA",
    slug: "iphone-12-pro-256gb-ex-usa",
    description:
      "Apple iPhone 12 Pro 256GB, Ex USA. Excellent condition, fully tested, 90-day warranty.",
    category: "iphones",
    brand: "Apple",
    condition: "ex-usa",
    price: 50000,
    images: [`${PH}iPhone+12+Pro`],
    specs: {
      Storage: "256GB",
      Chip: "A14 Bionic",
      Display: "6.1-inch Super Retina XDR",
      Grade: "Grade A",
    },
    stock: 8,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: false,
  },
  {
    name: "iPhone 12 Pro Max — Ex USA",
    slug: "iphone-12-pro-max-ex-usa",
    description:
      "Apple iPhone 12 Pro Max, Ex USA. Excellent condition, fully tested, 90-day warranty.",
    category: "iphones",
    brand: "Apple",
    condition: "ex-usa",
    price: 54000,
    images: [`${PH}iPhone+12+Pro+Max`],
    specs: { Chip: "A14 Bionic", Display: "6.7-inch Super Retina XDR", Grade: "Grade A" },
    stock: 10,
    isActive: true,
    isFeatured: false,
    isHotDeal: true,
    isNewArrival: false,
    variants: [
      { storage: "128GB", price: 54000, stock: 6 },
      { storage: "256GB", price: 58000, stock: 4 },
    ],
  },
  {
    name: "iPhone 13 — Ex USA",
    slug: "iphone-13-ex-usa",
    description:
      "Apple iPhone 13, Ex USA. A15 Bionic, dual camera, excellent battery life. 90-day warranty.",
    category: "iphones",
    brand: "Apple",
    condition: "ex-usa",
    price: 48000,
    images: [`${PH}iPhone+13`],
    specs: { Chip: "A15 Bionic", Display: "6.1-inch Super Retina XDR", Grade: "Grade A" },
    stock: 15,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: false,
    variants: [
      { storage: "128GB", price: 48000, stock: 6 },
      { storage: "256GB", price: 51000, stock: 5 },
      { storage: "512GB", price: 53000, stock: 4 },
    ],
  },
  {
    name: "iPhone 13 Pro — Ex USA",
    slug: "iphone-13-pro-ex-usa",
    description:
      "Apple iPhone 13 Pro, Ex USA. ProMotion 120Hz display, A15 Bionic, pro camera system. 90-day warranty.",
    category: "iphones",
    brand: "Apple",
    condition: "ex-usa",
    price: 60000,
    images: [`${PH}iPhone+13+Pro`],
    specs: { Chip: "A15 Bionic", Display: "6.1-inch ProMotion 120Hz", Grade: "Grade A" },
    stock: 12,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: false,
    variants: [
      { storage: "128GB", price: 60000, stock: 5 },
      { storage: "256GB", price: 65000, stock: 4 },
      { storage: "1TB", price: 70000, stock: 3 },
    ],
  },
  {
    name: "iPhone 13 Pro Max — Ex USA",
    slug: "iphone-13-pro-max-ex-usa",
    description:
      "Apple iPhone 13 Pro Max, Ex USA. Largest Pro display, A15 Bionic, 4352mAh battery. 90-day warranty.",
    category: "iphones",
    brand: "Apple",
    condition: "ex-usa",
    price: 65000,
    images: [`${PH}iPhone+13+Pro+Max`],
    specs: { Chip: "A15 Bionic", Display: "6.7-inch ProMotion 120Hz", Grade: "Grade A" },
    stock: 10,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: false,
    variants: [
      { storage: "128GB", price: 65000, stock: 4 },
      { storage: "256GB", price: 73000, stock: 3 },
      { storage: "512GB", price: 75000, stock: 3 },
    ],
  },
  {
    name: "iPhone 14 — Ex USA",
    slug: "iphone-14-ex-usa",
    description:
      "Apple iPhone 14, Ex USA. A15 Bionic, Crash Detection, Emergency SOS via satellite. 90-day warranty.",
    category: "iphones",
    brand: "Apple",
    condition: "ex-usa",
    price: 55000,
    images: [`${PH}iPhone+14`],
    specs: { Chip: "A15 Bionic", Display: "6.1-inch Super Retina XDR", Grade: "Grade A" },
    stock: 10,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: false,
    variants: [
      { storage: "128GB", price: 55000, stock: 5 },
      { storage: "256GB", price: 60000, stock: 5 },
    ],
  },
  {
    name: "iPhone 14 Pro — Ex USA",
    slug: "iphone-14-pro-ex-usa",
    description:
      "Apple iPhone 14 Pro, Ex USA. Dynamic Island, 48MP camera, Always-On Display. 90-day warranty.",
    category: "iphones",
    brand: "Apple",
    condition: "ex-usa",
    price: 75000,
    images: [`${PH}iPhone+14+Pro`],
    specs: {
      Storage: "256GB",
      Chip: "A16 Bionic",
      Display: "6.1-inch ProMotion 120Hz",
      Grade: "Grade A",
    },
    stock: 7,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: false,
  },
  {
    name: "iPhone 14 Pro Max — Ex USA",
    slug: "iphone-14-pro-max-ex-usa",
    description:
      "Apple iPhone 14 Pro Max, Ex USA. Largest Pro, Dynamic Island, 48MP, Always-On Display. 90-day warranty.",
    category: "iphones",
    brand: "Apple",
    condition: "ex-usa",
    price: 85000,
    images: [`${PH}iPhone+14+Pro+Max`],
    specs: {
      Storage: "256GB",
      Chip: "A16 Bionic",
      Display: "6.7-inch ProMotion 120Hz",
      Grade: "Grade A",
    },
    stock: 6,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: false,
  },
  {
    name: "iPhone 15 — Ex USA",
    slug: "iphone-15-ex-usa",
    description: "Apple iPhone 15, Ex USA. A16 Bionic, USB-C, 48MP main camera. 90-day warranty.",
    category: "iphones",
    brand: "Apple",
    condition: "ex-usa",
    price: 70000,
    images: [`${PH}iPhone+15`],
    specs: {
      Storage: "128GB",
      Chip: "A16 Bionic",
      Display: "6.1-inch Super Retina XDR",
      Connector: "USB-C",
      Grade: "Grade A",
    },
    stock: 8,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: false,
  },
  {
    name: "iPhone 15 Pro Max — Ex USA",
    slug: "iphone-15-pro-max-ex-usa",
    description:
      "Apple iPhone 15 Pro Max, Ex USA. Titanium frame, A17 Pro, 5x optical zoom. 90-day warranty.",
    category: "iphones",
    brand: "Apple",
    condition: "ex-usa",
    price: 105000,
    images: [`${PH}iPhone+15+Pro+Max`],
    specs: {
      Chip: "A17 Pro",
      Display: "6.7-inch ProMotion 120Hz",
      Frame: "Titanium",
      Grade: "Grade A",
    },
    stock: 8,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: false,
    variants: [
      { storage: "256GB", price: 105000, stock: 5 },
      { storage: "512GB", price: 110000, stock: 3 },
    ],
  },
  {
    name: "iPhone 16 Pro Max — Ex USA",
    slug: "iphone-16-pro-max-ex-usa",
    description:
      "Apple iPhone 16 Pro Max, Ex USA. A18 Pro chip, Camera Control button, 5x optical zoom. 90-day warranty.",
    category: "iphones",
    brand: "Apple",
    condition: "ex-usa",
    price: 125000,
    images: [`${PH}iPhone+16+Pro+Max`],
    specs: {
      Chip: "A18 Pro",
      Display: "6.9-inch ProMotion 120Hz",
      Frame: "Titanium",
      Grade: "Grade A",
    },
    stock: 8,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "256GB", price: 125000, stock: 5 },
      { storage: "512GB", price: 135000, stock: 3 },
    ],
  },
  {
    name: "iPhone 17 Pro — Ex USA",
    slug: "iphone-17-pro-ex-usa",
    description:
      "Apple iPhone 17 Pro, Ex USA. Latest Pro model with A19 Pro chip, 256GB. 90-day warranty.",
    category: "iphones",
    brand: "Apple",
    condition: "ex-usa",
    price: 170000,
    images: [`${PH}iPhone+17+Pro`],
    specs: { Storage: "256GB", Chip: "A19 Pro", Frame: "Titanium", Grade: "Grade A" },
    stock: 5,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
  },

  // ─── EX-UK Samsungs ───────────────────────────────────────────────
  {
    name: "Samsung Galaxy S23 Ultra — Ex UK",
    slug: "samsung-s23-ultra-ex-uk",
    description:
      "Samsung Galaxy S23 Ultra, 512GB, Ex UK. Built-in S Pen, 200MP camera, Snapdragon 8 Gen 2. 90-day warranty.",
    category: "samsung",
    brand: "Samsung",
    condition: "ex-uk",
    price: 75000,
    images: [`${PH}Samsung+S23+Ultra`],
    specs: {
      Storage: "512GB",
      Chip: "Snapdragon 8 Gen 2",
      Display: "6.8-inch Dynamic AMOLED 120Hz",
      Camera: "200MP",
      Grade: "Grade A",
    },
    stock: 8,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: false,
  },
  {
    name: "Samsung Galaxy S24+ — Ex UK",
    slug: "samsung-s24-plus-ex-uk",
    description:
      "Samsung Galaxy S24+, 512GB, Ex UK. Galaxy AI, Snapdragon 8 Gen 3, 50MP camera. 90-day warranty.",
    category: "samsung",
    brand: "Samsung",
    condition: "ex-uk",
    price: 70000,
    images: [`${PH}Samsung+S24+Plus`],
    specs: {
      Storage: "512GB",
      Chip: "Snapdragon 8 Gen 3",
      Display: "6.7-inch Dynamic AMOLED 120Hz",
      Grade: "Grade A",
    },
    stock: 6,
    isActive: true,
    isFeatured: false,
    isHotDeal: true,
    isNewArrival: false,
  },
  {
    name: "Samsung Galaxy S24 Ultra — Ex UK",
    slug: "samsung-s24-ultra-ex-uk",
    description:
      "Samsung Galaxy S24 Ultra, Ex UK. Titanium frame, S Pen, 200MP quad camera, Galaxy AI. 90-day warranty.",
    category: "samsung",
    brand: "Samsung",
    condition: "ex-uk",
    price: 92000,
    images: [`${PH}Samsung+S24+Ultra`],
    specs: {
      Chip: "Snapdragon 8 Gen 3",
      Display: "6.8-inch Dynamic AMOLED 120Hz",
      Camera: "200MP",
      Grade: "Grade A",
    },
    stock: 8,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: false,
    variants: [
      { storage: "256GB", price: 92000, stock: 4 },
      { storage: "512GB", price: 98000, stock: 4 },
    ],
  },
  {
    name: "Samsung Galaxy Z Fold 6 — Ex UK",
    slug: "samsung-fold-6-ex-uk",
    description:
      "Samsung Galaxy Z Fold 6, Ex UK. Foldable flagship, Snapdragon 8 Gen 3, dual displays. 90-day warranty.",
    category: "samsung",
    brand: "Samsung",
    condition: "ex-uk",
    price: 105000,
    images: [`${PH}Samsung+Fold+6`],
    specs: {
      Chip: "Snapdragon 8 Gen 3",
      MainDisplay: "7.6-inch QXGA+",
      CoverDisplay: "6.3-inch FHD+",
      Grade: "Grade A",
    },
    stock: 6,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: false,
    variants: [
      { storage: "256GB", price: 105000, stock: 2 },
      { storage: "512GB", price: 110000, stock: 2 },
      { storage: "1TB", price: 115000, stock: 2 },
    ],
  },
  {
    name: "Samsung Galaxy Z Fold 7 — Ex UK",
    slug: "samsung-fold-7-ex-uk",
    description:
      "Samsung Galaxy Z Fold 7, 512GB, Ex UK. Latest foldable with slimmer form factor. 90-day warranty.",
    category: "samsung",
    brand: "Samsung",
    condition: "ex-uk",
    price: 165000,
    images: [`${PH}Samsung+Fold+7`],
    specs: { Storage: "512GB", Display: "7.9-inch Foldable", Grade: "Grade A" },
    stock: 3,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
  },

  // ─── Brand New iPhones (Physical SIM) ────────────────────────────
  {
    name: "iPhone 16 — Brand New",
    slug: "iphone-16-brand-new",
    description:
      "Brand new Apple iPhone 16, sealed box, Physical SIM. A18 chip, Camera Control, USB-C.",
    category: "iphones",
    brand: "Apple",
    condition: "brand-new",
    price: 105000,
    images: [`${PH}iPhone+16`],
    specs: { Chip: "A18", Display: "6.1-inch Super Retina XDR", Connector: "USB-C" },
    stock: 10,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "128GB", simType: "physical-sim", price: 105000, stock: 5 },
      { storage: "256GB", simType: "physical-sim", price: 115000, stock: 5 },
    ],
  },
  {
    name: "iPhone 17 — Brand New",
    slug: "iphone-17-brand-new",
    description:
      "Brand new Apple iPhone 17, sealed box. A19 chip, next-generation camera system, USB-C.",
    category: "iphones",
    brand: "Apple",
    condition: "brand-new",
    price: 130000,
    images: [`${PH}iPhone+17`],
    specs: { Chip: "A19", Display: "6.1-inch Super Retina XDR", Connector: "USB-C" },
    stock: 8,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "256GB", simType: "physical-sim", price: 130000, stock: 4 },
      { storage: "256GB", simType: "esim", price: 130000, stock: 4 },
    ],
  },
  {
    name: "iPhone 17 Pro — Brand New",
    slug: "iphone-17-pro-brand-new",
    description:
      "Brand new Apple iPhone 17 Pro, sealed box. A19 Pro chip, titanium frame, pro camera system.",
    category: "iphones",
    brand: "Apple",
    condition: "brand-new",
    price: 182000,
    images: [`${PH}iPhone+17+Pro`],
    specs: { Chip: "A19 Pro", Display: "6.3-inch ProMotion 120Hz", Frame: "Titanium" },
    stock: 12,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "256GB", simType: "physical-sim", color: "Orange", price: 185000, stock: 3 },
      { storage: "256GB", simType: "physical-sim", color: "Silver", price: 188000, stock: 3 },
      { storage: "256GB", simType: "esim", color: "Blue", price: 182000, stock: 3 },
      { storage: "256GB", simType: "esim", color: "Orange", price: 182000, stock: 3 },
    ],
  },
  {
    name: "iPhone 17 Pro Max — Brand New",
    slug: "iphone-17-pro-max-brand-new",
    description:
      "Brand new Apple iPhone 17 Pro Max, sealed box. A19 Pro chip, titanium, largest Pro display.",
    category: "iphones",
    brand: "Apple",
    condition: "brand-new",
    price: 190000,
    images: [`${PH}iPhone+17+Pro+Max`],
    specs: { Chip: "A19 Pro", Display: "6.9-inch ProMotion 120Hz", Frame: "Titanium" },
    stock: 15,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "256GB", simType: "physical-sim", color: "Orange", price: 205000, stock: 2 },
      { storage: "256GB", simType: "physical-sim", color: "Blue", price: 205000, stock: 2 },
      { storage: "256GB", simType: "physical-sim", color: "Silver", price: 205000, stock: 2 },
      { storage: "256GB", simType: "esim", color: "Orange", price: 190000, stock: 2 },
      { storage: "256GB", simType: "esim", color: "Blue", price: 190000, stock: 2 },
      { storage: "512GB", simType: "physical-sim", color: "Orange", price: 230000, stock: 2 },
      { storage: "512GB", simType: "esim", color: "Orange", price: 215000, stock: 3 },
    ],
  },
  {
    name: "iPhone 17 Air — Brand New",
    slug: "iphone-17-air-brand-new",
    description: "Brand new Apple iPhone 17 Air, sealed box. Ultra-thin design, A19 chip, eSIM.",
    category: "iphones",
    brand: "Apple",
    condition: "brand-new",
    price: 135000,
    images: [`${PH}iPhone+17+Air`],
    specs: { Chip: "A19", Display: "6.6-inch Super Retina XDR", Design: "Ultra-thin" },
    stock: 8,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "256GB", simType: "esim", price: 135000, stock: 4 },
      { storage: "512GB", simType: "esim", price: 155000, stock: 4 },
    ],
  },

  // ─── Brand New Samsungs ──────────────────────────────────────────
  {
    name: "Samsung Galaxy S25 Ultra — Brand New",
    slug: "samsung-s25-ultra-brand-new",
    description:
      "Brand new Samsung Galaxy S25 Ultra, sealed. S Pen, 200MP camera, Snapdragon 8 Elite.",
    category: "samsung",
    brand: "Samsung",
    condition: "brand-new",
    price: 130000,
    images: [`${PH}Samsung+S25+Ultra`],
    specs: {
      Storage: "256GB",
      Chip: "Snapdragon 8 Elite",
      Display: "6.9-inch Dynamic AMOLED 120Hz",
      Camera: "200MP",
    },
    stock: 6,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    name: "Samsung Galaxy S26 — Brand New",
    slug: "samsung-s26-brand-new",
    description:
      "Brand new Samsung Galaxy S26, sealed. Latest Galaxy flagship with next-gen AI features.",
    category: "samsung",
    brand: "Samsung",
    condition: "brand-new",
    price: 110000,
    images: [`${PH}Samsung+S26`],
    specs: { Storage: "256GB", Display: "6.2-inch Dynamic AMOLED 120Hz" },
    stock: 5,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    name: "Samsung Galaxy S26 Ultra — Brand New",
    slug: "samsung-s26-ultra-brand-new",
    description:
      "Brand new Samsung Galaxy S26 Ultra, sealed. S Pen, pro-grade cameras, AI powerhouse.",
    category: "samsung",
    brand: "Samsung",
    condition: "brand-new",
    price: 155000,
    images: [`${PH}Samsung+S26+Ultra`],
    specs: { Display: "7.0-inch Dynamic AMOLED 120Hz", Region: "East Africa" },
    stock: 8,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "256GB", price: 155000, stock: 4 },
      { storage: "512GB", price: 165000, stock: 2 },
      { storage: "1TB", price: 213000, stock: 2 },
    ],
  },
  {
    name: "Samsung Galaxy Z Flip 7 — Brand New",
    slug: "samsung-flip-7-brand-new",
    description:
      "Brand new Samsung Galaxy Z Flip 7, sealed. Compact foldable with large cover display.",
    category: "samsung",
    brand: "Samsung",
    condition: "brand-new",
    price: 117000,
    images: [`${PH}Samsung+Flip+7`],
    specs: { Storage: "256GB", MainDisplay: "6.7-inch AMOLED 120Hz", CoverDisplay: "3.4-inch" },
    stock: 5,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    name: "Samsung Galaxy Z Fold 7 — Brand New",
    slug: "samsung-fold-7-brand-new",
    description:
      "Brand new Samsung Galaxy Z Fold 7, sealed. Latest foldable flagship, Book-style form factor.",
    category: "samsung",
    brand: "Samsung",
    condition: "brand-new",
    price: 195000,
    images: [`${PH}Samsung+Fold+7+New`],
    specs: { MainDisplay: "7.9-inch Foldable AMOLED", CoverDisplay: "6.5-inch FHD+" },
    stock: 4,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "256GB", price: 195000, stock: 2 },
      { storage: "512GB", price: 205000, stock: 2 },
    ],
  },
  {
    name: "Samsung Galaxy Z Trifold — Brand New",
    slug: "samsung-trifold-brand-new",
    description:
      "Brand new Samsung Galaxy Z Trifold, sealed. World's first triple-fold smartphone.",
    category: "samsung",
    brand: "Samsung",
    condition: "brand-new",
    price: 600000,
    images: [`${PH}Samsung+Trifold`],
    specs: { Display: "Triple-fold AMOLED" },
    stock: 2,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
  },

  // ─── Apple Watch ─────────────────────────────────────────────────
  {
    name: "Apple Watch Series 10 — Brand New",
    slug: "apple-watch-series-10",
    description:
      "Brand new Apple Watch Series 10. Thinnest Apple Watch ever, sleep apnea detection, Always-On Display.",
    category: "wearables",
    brand: "Apple",
    condition: "brand-new",
    price: 46000,
    images: [`${PH}Apple+Watch+S10`],
    specs: {
      Chip: "S10",
      WatchOS: "watchOS 11",
      Features: "Sleep Apnea Detection, Always-On Display",
    },
    stock: 10,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "42mm", price: 46000, stock: 5 },
      { storage: "46mm", price: 52000, stock: 5 },
    ],
  },
  {
    name: "Apple Watch Series 11 — Brand New",
    slug: "apple-watch-series-11",
    description: "Brand new Apple Watch Series 11. Next-gen health sensors, latest watchOS.",
    category: "wearables",
    brand: "Apple",
    condition: "brand-new",
    price: 55000,
    images: [`${PH}Apple+Watch+S11`],
    specs: { WatchOS: "Latest watchOS" },
    stock: 8,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "42mm", price: 55000, stock: 4 },
      { storage: "46mm", price: 60000, stock: 4 },
    ],
  },
  {
    name: "Apple Watch SE 3 — Brand New",
    slug: "apple-watch-se-3",
    description:
      "Brand new Apple Watch SE 3. Best value Apple Watch with essential health and safety features.",
    category: "wearables",
    brand: "Apple",
    condition: "brand-new",
    price: 38000,
    images: [`${PH}Apple+Watch+SE+3`],
    specs: { Chip: "S8", Features: "Crash Detection, Emergency SOS, Fitness Tracking" },
    stock: 12,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "40mm", price: 38000, stock: 6 },
      { storage: "44mm", price: 42000, stock: 6 },
    ],
  },
  {
    name: "Apple Watch Ultra 2 — Brand New",
    slug: "apple-watch-ultra-2",
    description:
      "Brand new Apple Watch Ultra 2. Titanium case, 36-hour battery, precision GPS, 3000 nits display.",
    category: "wearables",
    brand: "Apple",
    condition: "brand-new",
    price: 95000,
    images: [`${PH}Apple+Watch+Ultra+2`],
    specs: {
      Case: "Titanium",
      Battery: "36 hours",
      Display: "49mm, 3000 nits",
      GPS: "L1+L5 dual-frequency",
    },
    stock: 5,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: false,
  },
  {
    name: "Apple Watch Ultra 3 — Brand New",
    slug: "apple-watch-ultra-3",
    description:
      "Brand new Apple Watch Ultra 3. Latest Ultra with improved health sensors and extended battery life.",
    category: "wearables",
    brand: "Apple",
    condition: "brand-new",
    price: 105000,
    images: [`${PH}Apple+Watch+Ultra+3`],
    specs: { Case: "Titanium", Battery: "60 hours Low Power Mode", Display: "49mm" },
    stock: 4,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    name: "Apple Watch Ultra 2025 — Brand New",
    slug: "apple-watch-ultra-2025",
    description:
      "Brand new Apple Watch Ultra (2025), 49mm. Carbon-neutral black titanium or natural titanium.",
    category: "wearables",
    brand: "Apple",
    condition: "brand-new",
    price: 52000,
    images: [`${PH}Apple+Watch+Ultra+2025`],
    specs: { Size: "49mm", Case: "Titanium" },
    stock: 6,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    name: "Apple Watch Series 6 40mm — Brand New",
    slug: "apple-watch-series-6-40mm",
    description:
      "Brand new Apple Watch Series 6, 40mm. Blood oxygen sensor, ECG, Always-On Retina display.",
    category: "wearables",
    brand: "Apple",
    condition: "brand-new",
    price: 24000,
    images: [`${PH}Apple+Watch+S6`],
    specs: { Size: "40mm", Chip: "S6", Features: "Blood Oxygen, ECG, Always-On Display" },
    stock: 8,
    isActive: true,
    isFeatured: false,
    isHotDeal: true,
    isNewArrival: false,
  },
  {
    name: "Apple Watch Series 7 44mm — Brand New",
    slug: "apple-watch-series-7-44mm",
    description:
      "Brand new Apple Watch Series 7, 44mm. Largest, most durable display, fast charging.",
    category: "wearables",
    brand: "Apple",
    condition: "brand-new",
    price: 27000,
    images: [`${PH}Apple+Watch+S7`],
    specs: { Size: "44mm", Chip: "S7", Features: "Crack-resistant display, Fast charging" },
    stock: 8,
    isActive: true,
    isFeatured: false,
    isHotDeal: true,
    isNewArrival: false,
  },
  {
    name: "Apple Watch Series 8 — Brand New",
    slug: "apple-watch-series-8",
    description:
      "Brand new Apple Watch Series 8. Crash Detection, Cycle Tracking, temperature sensing.",
    category: "wearables",
    brand: "Apple",
    condition: "brand-new",
    price: 33000,
    images: [`${PH}Apple+Watch+S8`],
    specs: { Chip: "S8", Features: "Crash Detection, Temperature Sensing, Cycle Tracking" },
    stock: 10,
    isActive: true,
    isFeatured: false,
    isHotDeal: true,
    isNewArrival: false,
    variants: [
      { storage: "40mm", price: 33000, stock: 5 },
      { storage: "44mm", price: 35000, stock: 5 },
    ],
  },

  // ─── MacBook Air ─────────────────────────────────────────────────
  {
    name: "MacBook Air Neo — Brand New",
    slug: "macbook-air-neo",
    description: "Brand new MacBook Air Neo. Brilliant display, fanless design, all-day battery.",
    category: "mac",
    brand: "Apple",
    condition: "brand-new",
    price: 115000,
    images: [`${PH}MacBook+Air+Neo`],
    specs: { RAM: "16GB", Storage: "256GB SSD" },
    stock: 5,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    name: "MacBook Air M4 — Brand New",
    slug: "macbook-air-m4",
    description:
      "Brand new MacBook Air M4. Apple M4 chip, 16GB RAM, 512GB SSD, 15.3-inch Liquid Retina display.",
    category: "mac",
    brand: "Apple",
    condition: "brand-new",
    price: 165000,
    images: [`${PH}MacBook+Air+M4`],
    specs: {
      Chip: "Apple M4",
      RAM: "16GB",
      Storage: "512GB SSD",
      Display: "15.3-inch Liquid Retina",
    },
    stock: 5,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    name: "MacBook Air M5 — Brand New",
    slug: "macbook-air-m5",
    description:
      "Brand new MacBook Air M5. Apple M5 chip, fanless, all-day battery, up to 1TB SSD.",
    category: "mac",
    brand: "Apple",
    condition: "brand-new",
    price: 175000,
    images: [`${PH}MacBook+Air+M5`],
    specs: { Chip: "Apple M5", RAM: "16GB", Display: "Liquid Retina" },
    stock: 6,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "512GB", price: 175000, stock: 3 },
      { storage: "1TB", price: 200000, stock: 3 },
    ],
  },
  {
    name: "MacBook Pro M5 — Brand New",
    slug: "macbook-pro-m5",
    description:
      "Brand new MacBook Pro M5. Pro-level performance, Liquid Retina XDR display, up to 24GB RAM.",
    category: "mac",
    brand: "Apple",
    condition: "brand-new",
    price: 225000,
    images: [`${PH}MacBook+Pro+M5`],
    specs: { Chip: "Apple M5", Display: "Liquid Retina XDR" },
    stock: 4,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "512GB", simType: undefined, color: undefined, price: 225000, stock: 2 },
      { storage: "1TB", simType: undefined, color: undefined, price: 280000, stock: 2 },
    ],
  },
  {
    name: "Mac Mini M4 — Brand New",
    slug: "mac-mini-m4",
    description:
      "Brand new Mac Mini M4. Most powerful and affordable Mac desktop, 16GB RAM, 256GB SSD.",
    category: "mac",
    brand: "Apple",
    condition: "brand-new",
    price: 90000,
    images: [`${PH}Mac+Mini+M4`],
    specs: {
      Chip: "Apple M4",
      RAM: "16GB",
      Storage: "256GB SSD",
      Ports: "3x Thunderbolt 4, USB-A, HDMI, Ethernet",
    },
    stock: 6,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
  },

  // ─── iPad ─────────────────────────────────────────────────────────
  {
    name: "iPad 10th Gen — Brand New",
    slug: "ipad-10th-gen",
    description: "Brand new iPad 10th Generation. A14 Bionic, USB-C, landscape front camera.",
    category: "ipad",
    brand: "Apple",
    condition: "brand-new",
    price: 55000,
    images: [`${PH}iPad+10th+Gen`],
    specs: {
      Chip: "A14 Bionic",
      Display: "10.9-inch Liquid Retina",
      Storage: "64GB",
      Connector: "USB-C",
    },
    stock: 8,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: false,
    variants: [
      { storage: "64GB", simType: "wifi-5g", price: 55000, stock: 4 },
      { storage: "64GB", simType: "wifi", price: 65000, stock: 4 },
    ],
  },
  {
    name: "iPad 11th Gen A16 — Brand New",
    slug: "ipad-11th-gen-a16",
    description: "Brand new iPad 11th Generation with A16 chip. USB-C, Apple Pencil Pro support.",
    category: "ipad",
    brand: "Apple",
    condition: "brand-new",
    price: 65000,
    images: [`${PH}iPad+11th+Gen`],
    specs: {
      Chip: "A16 Bionic",
      Display: "10.9-inch Liquid Retina",
      Storage: "128GB",
      Connector: "USB-C",
    },
    stock: 8,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "128GB", simType: "wifi", price: 65000, stock: 4 },
      { storage: "128GB", simType: "wifi-5g", price: 75000, stock: 4 },
    ],
  },
  {
    name: 'iPad Air 13" M3 — Brand New',
    slug: "ipad-air-13-m3",
    description:
      "Brand new iPad Air 13-inch M3. Largest Air yet, landscape front camera, Apple Pencil Pro support.",
    category: "ipad",
    brand: "Apple",
    condition: "brand-new",
    price: 108000,
    images: [`${PH}iPad+Air+13+M3`],
    specs: { Chip: "Apple M3", Display: "13-inch Liquid Retina", Storage: "128GB" },
    stock: 5,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "128GB", simType: "wifi", price: 108000, stock: 3 },
      { storage: "128GB", simType: "wifi-5g", price: 110000, stock: 2 },
    ],
  },
  {
    name: 'iPad Air 11" M3 — Brand New',
    slug: "ipad-air-11-m3",
    description:
      "Brand new iPad Air 11-inch M3. Apple M3 chip, USB-C, Apple Pencil Pro compatible.",
    category: "ipad",
    brand: "Apple",
    condition: "brand-new",
    price: 108000,
    images: [`${PH}iPad+Air+11+M3`],
    specs: { Chip: "Apple M3", Display: "11-inch Liquid Retina", Storage: "128GB" },
    stock: 5,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "128GB", simType: "wifi", price: 108000, stock: 3 },
      { storage: "128GB", simType: "wifi-5g", price: 110000, stock: 2 },
    ],
  },
  {
    name: "iPad Mini A17 Pro — Brand New",
    slug: "ipad-mini-a17-pro",
    description:
      "Brand new iPad Mini A17 Pro. Pocket-sized powerhouse, Apple Intelligence, Apple Pencil Pro support.",
    category: "ipad",
    brand: "Apple",
    condition: "brand-new",
    price: 70000,
    images: [`${PH}iPad+Mini+A17`],
    specs: { Chip: "A17 Pro", Display: "8.3-inch Liquid Retina", Storage: "128GB" },
    stock: 6,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    name: 'iPad Pro 11" M5 — Brand New',
    slug: "ipad-pro-11-m5",
    description:
      "Brand new iPad Pro 11-inch M5. Ultra Retina XDR OLED, Apple Pencil Pro, 5G capable.",
    category: "ipad",
    brand: "Apple",
    condition: "brand-new",
    price: 165000,
    images: [`${PH}iPad+Pro+11+M5`],
    specs: { Chip: "Apple M5", Display: "11-inch Ultra Retina XDR OLED", Storage: "256GB" },
    stock: 4,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "256GB", simType: "wifi-5g", price: 165000, stock: 2 },
      { storage: "256GB", simType: "wifi", price: 155000, stock: 2 },
    ],
  },
  {
    name: 'iPad Pro 13" M5 — Brand New',
    slug: "ipad-pro-13-m5",
    description:
      "Brand new iPad Pro 13-inch M5. Largest Ultra Retina XDR OLED, Apple Pencil Pro, Magic Keyboard support.",
    category: "ipad",
    brand: "Apple",
    condition: "brand-new",
    price: 178000,
    images: [`${PH}iPad+Pro+13+M5`],
    specs: { Chip: "Apple M5", Display: "13-inch Ultra Retina XDR OLED", Storage: "256GB" },
    stock: 3,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
    variants: [
      { storage: "256GB", simType: "wifi-5g", price: 178000, stock: 2 },
      { storage: "256GB", simType: "wifi", price: 168000, stock: 1 },
    ],
  },

  // ─── Accessories — Apple Pencil, AirTag, Mouse, Trackpad, Keyboard ─
  {
    name: "Apple Pencil Pro — Brand New",
    slug: "apple-pencil-pro",
    description:
      "Brand new Apple Pencil Pro. Squeeze gesture, Find My, double-tap, pixel-perfect precision.",
    category: "accessories",
    brand: "Apple",
    condition: "brand-new",
    price: 22000,
    images: [`${PH}Apple+Pencil+Pro`],
    specs: {
      Compatible: "iPad Pro M4+, iPad Air M2+, iPad Mini A17 Pro",
      Charging: "Magnetic wireless",
    },
    stock: 15,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    name: "Apple Pencil 2nd Generation — Brand New",
    slug: "apple-pencil-2nd-gen",
    description:
      "Brand new Apple Pencil 2nd Generation. Magnetic wireless charging, double-tap to switch tools.",
    category: "accessories",
    brand: "Apple",
    condition: "brand-new",
    price: 16000,
    images: [`${PH}Apple+Pencil+2`],
    specs: { Compatible: 'iPad Pro 11"/12.9", iPad Air 4+', Charging: "Magnetic wireless" },
    stock: 12,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: false,
  },
  {
    name: "Apple Pencil USB-C — Brand New",
    slug: "apple-pencil-usbc",
    description:
      "Brand new Apple Pencil (USB-C). Affordable precision stylus for compatible iPad models.",
    category: "accessories",
    brand: "Apple",
    condition: "brand-new",
    price: 17000,
    images: [`${PH}Apple+Pencil+USB-C`],
    specs: { Compatible: "iPad with USB-C", Charging: "USB-C" },
    stock: 12,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: false,
  },
  {
    name: "AirTag 1-Pack — Brand New",
    slug: "airtag-1-pack",
    description:
      "Brand new Apple AirTag 1-pack. Track keys, bags, and anything important with Precision Finding.",
    category: "accessories",
    brand: "Apple",
    condition: "brand-new",
    price: 9000,
    images: [`${PH}AirTag`],
    specs: { Battery: "CR2032", Range: "Bluetooth + Ultra Wideband", Network: "Find My" },
    stock: 20,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: false,
  },
  {
    name: "AirTag 4-Pack — Brand New",
    slug: "airtag-4-pack",
    description:
      "Brand new Apple AirTag 4-pack. Track four items at once — save versus buying individually.",
    category: "accessories",
    brand: "Apple",
    condition: "brand-new",
    price: 18000,
    images: [`${PH}AirTag+4Pack`],
    specs: { Contents: "4 AirTags", Battery: "CR2032 each", Network: "Find My" },
    stock: 15,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: false,
  },
  {
    name: "Magic Mouse — Brand New",
    slug: "magic-mouse",
    description:
      "Brand new Apple Magic Mouse. Multi-Touch surface, rechargeable, works with any Mac.",
    category: "accessories",
    brand: "Apple",
    condition: "brand-new",
    price: 14000,
    images: [`${PH}Magic+Mouse`],
    specs: { Connectivity: "Bluetooth", Charging: "Lightning" },
    stock: 10,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: false,
    variants: [
      { storage: "Magic Mouse 2", price: 14000, stock: 4 },
      { storage: "Magic Mouse 3", price: 17000, stock: 3 },
      { storage: "Magic Mouse 4", price: 19000, stock: 3 },
    ],
  },
  {
    name: "Magic Trackpad — Brand New",
    slug: "magic-trackpad",
    description:
      "Brand new Apple Magic Trackpad. Force Touch, gesture support, rechargeable, works with any Mac.",
    category: "accessories",
    brand: "Apple",
    condition: "brand-new",
    price: 23000,
    images: [`${PH}Magic+Trackpad`],
    specs: { Connectivity: "Bluetooth", Charging: "Lightning" },
    stock: 8,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: false,
    variants: [
      { storage: "White", price: 23000, stock: 4 },
      { storage: "Black", price: 25000, stock: 4 },
    ],
  },
  {
    name: "Magic Keyboard — Brand New",
    slug: "magic-keyboard",
    description:
      "Brand new Apple Magic Keyboard. Comfortable scissor keys, rechargeable, wireless.",
    category: "accessories",
    brand: "Apple",
    condition: "brand-new",
    price: 18000,
    images: [`${PH}Magic+Keyboard`],
    specs: { Connectivity: "Bluetooth", Charging: "Lightning" },
    stock: 10,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: false,
    variants: [
      { storage: "Standard", price: 18000, stock: 5 },
      { storage: "USB-C", price: 20000, stock: 5 },
    ],
  },
  {
    name: "Apple TV 4K — Brand New",
    slug: "apple-tv-4k",
    description: "Brand new Apple TV 4K. A15 Bionic, 4K HDR, Dolby Atmos, Siri Remote.",
    category: "accessories",
    brand: "Apple",
    condition: "brand-new",
    price: 26000,
    images: [`${PH}Apple+TV+4K`],
    specs: { Chip: "A15 Bionic", Resolution: "4K HDR", Audio: "Dolby Atmos" },
    stock: 8,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: false,
    variants: [
      { storage: "64GB", price: 26000, stock: 4 },
      { storage: "128GB", price: 30000, stock: 4 },
    ],
  },

  // ─── Audio ────────────────────────────────────────────────────────
  {
    name: "AirPods Max USB-C — Brand New",
    slug: "airpods-max-usbc",
    description:
      "Brand new AirPods Max with USB-C. Premium over-ear headphones, Active Noise Cancellation, Spatial Audio.",
    category: "audio",
    brand: "Apple",
    condition: "brand-new",
    price: 70000,
    images: [`${PH}AirPods+Max`],
    specs: {
      ANC: "Active Noise Cancellation",
      Transparency: "Adaptive Transparency",
      Battery: "20 hours",
      Chip: "H2",
    },
    stock: 6,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    name: "AirPods Pro 3 — Brand New",
    slug: "airpods-pro-3",
    description: "Brand new AirPods Pro 3. Hearing health features, ANC 2.0, H2 chip, USB-C case.",
    category: "audio",
    brand: "Apple",
    condition: "brand-new",
    price: 38000,
    images: [`${PH}AirPods+Pro+3`],
    specs: { Chip: "H2", ANC: "Active Noise Cancellation", Case: "USB-C MagSafe" },
    stock: 12,
    isActive: true,
    isFeatured: true,
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    name: "AirPods 4 ANC — Brand New",
    slug: "airpods-4-anc",
    description:
      "Brand new AirPods 4 with Active Noise Cancellation. Open-ear design, H2 chip, USB-C.",
    category: "audio",
    brand: "Apple",
    condition: "brand-new",
    price: 25000,
    images: [`${PH}AirPods+4+ANC`],
    specs: { Chip: "H2", ANC: "Active Noise Cancellation", Design: "Open-ear" },
    stock: 15,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: true,
  },
  {
    name: "AirPods 4 — Brand New",
    slug: "airpods-4",
    description:
      "Brand new AirPods 4. Redesigned open-ear fit, H2 chip, USB-C case, Personalized Spatial Audio.",
    category: "audio",
    brand: "Apple",
    condition: "brand-new",
    price: 22000,
    images: [`${PH}AirPods+4`],
    specs: { Chip: "H2", Design: "Open-ear", Case: "USB-C" },
    stock: 20,
    isActive: true,
    isFeatured: false,
    isHotDeal: false,
    isNewArrival: false,
  },
];

export const clearAndSeed = mutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query("products").collect();
    await Promise.all(existing.map((p) => ctx.db.delete(p._id)));
    const ids = await Promise.all(products.map((p) => ctx.db.insert("products", p)));
    return { cleared: existing.length, seeded: ids.length };
  },
});

export const seedProducts = mutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query("products").collect();
    if (existing.length > 0) {
      return { message: "Already seeded — run clearAndSeed to replace", count: existing.length };
    }
    const ids = await Promise.all(products.map((p) => ctx.db.insert("products", p)));
    return { message: "Seeded successfully", count: ids.length };
  },
});
